# Generated by Django 4.2.7 on 2024-02-26 11:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='day',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
