# Generated by Django 4.2.7 on 2024-02-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0006_booking_client_booking_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bill',
            field=models.ManyToManyField(blank=True, null=True, related_name='procedure_bill', to='VetBooker.bill'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bills',
            field=models.ManyToManyField(blank=True, null=True, related_name='bills', to='VetBooker.bill'),
        ),
        migrations.AlterField(
            model_name='client',
            name='bookings',
            field=models.ManyToManyField(blank=True, null=True, related_name='client_bookings', to='VetBooker.booking'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pet',
            field=models.ManyToManyField(blank=True, null=True, related_name='pet_owner', to='VetBooker.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='bookings',
            field=models.ManyToManyField(blank=True, null=True, related_name='pet_bookings', to='VetBooker.booking'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='booking_comments', to='VetBooker.booking'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ManyToManyField(blank=True, null=True, related_name='owner_pet', to='VetBooker.client'),
        ),
    ]
