# Generated by Django 4.2.7 on 2024-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0007_alter_booking_bill_alter_client_bills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bill',
        ),
        migrations.AddField(
            model_name='booking',
            name='vet',
            field=models.ManyToManyField(null=True, related_name='booking_pet', to='VetBooker.vet'),
        ),
    ]
