# Generated by Django 4.2.7 on 2024-02-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0008_remove_booking_bill_booking_vet'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vet',
            field=models.ManyToManyField(null=True, related_name='booking_vet', to='VetBooker.vet'),
        ),
    ]
