# Generated by Django 4.2.7 on 2024-02-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0009_booking_title_alter_booking_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
