# Generated by Django 4.2.7 on 2024-02-28 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0010_alter_client_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='owner',
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_pet', to='VetBooker.client'),
        ),
    ]
