# Generated by Django 4.2.7 on 2024-03-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0012_alter_booking_client_alter_booking_pet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vet',
            name='secondary_skills',
        ),
    ]
