# Generated by Django 4.2.7 on 2024-03-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0014_booking_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
    ]
