# Generated by Django 4.2.7 on 2024-05-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0015_remove_booking_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='vet',
        ),
        migrations.AddField(
            model_name='booking',
            name='vet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking_vet', to='VetBooker.vet'),
            preserve_default=False,
        ),
    ]
