# Generated by Django 4.2.7 on 2024-05-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0016_remove_booking_vet_booking_vet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='procedure',
            field=models.ManyToManyField(blank=True, null=True, related_name='booking_procedure', to='VetBooker.procedure'),
        ),
    ]
