# Generated by Django 4.2.7 on 2024-05-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0017_alter_booking_procedure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='procedure',
            field=models.ManyToManyField(blank=True, related_name='booking_procedure', to='VetBooker.procedure'),
        ),
    ]
