# Generated by Django 4.2.7 on 2024-05-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetBooker', '0018_alter_booking_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_access',
            field=models.BooleanField(default=False),
        ),
    ]
